version: "3.9"

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    env_file:
      - ./database.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:  # Add pgAdmin service
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: your_email@example.com
      PGADMIN_DEFAULT_PASSWORD: your_pgadmin_password
    ports:
      - "8080:80"
    depends_on:
      - postgres

volumes:
  postgres_data: